AccessSystem/Controllers/AdminUserController.cs
using AccessSystem.Model;
using AccessSystem.Repository;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.UI;

namespace AccessSystem.Controllers
{
    public class AdminUserController : Controller
    {
        static string ErrorMessage = string.Empty;
        static TBL_ADMINUSER holdAdminUser = new TBL_ADMINUSER();
        // GET: AdminUser
        public ActionResult ListScreen()
        {
            try
            {
                // reset error Message and hold data when going to list screen
                ErrorMessage = string.Empty;
                holdAdminUser = new TBL_ADMINUSER();

                if (string.IsNullOrEmpty(this.Session["ADMINID"].ToString()))
                {
                    return RedirectToAction("Login");
                }
                string adminAccountID = this.Session["ADMINID"].ToString();

                AdminModel adminModel = new AdminModel();
                adminModel.AccountInfo = AdminUserRepository.GetCurrentUserInfo(new Guid(adminAccountID));
                ViewBag.Firstname = adminModel.AccountInfo.FIRSTNAME;

                adminModel.AccountInfoList = AdminUserRepository.GetAllAdminUsers();

                return View(adminModel);
            }
            catch {
                return RedirectToAction("Login");
            }
        }

        public ActionResult EditScreen(Guid? AdminUserID)
        {
            try
            {
                if (string.IsNullOrEmpty(this.Session["ADMINID"].ToString()))
                {
                    return RedirectToAction("Login");
                }
                string adminAccountID = this.Session["ADMINID"].ToString();

                AdminModel adminModel = new AdminModel();
                adminModel.AccountInfo = AdminUserRepository.GetCurrentUserInfo(new Guid(adminAccountID));
                ViewBag.Firstname = adminModel.AccountInfo.FIRSTNAME;

                if(AdminUserID == null)
                {
                    ViewBag.EditScreenHeader = "Add Admin User";
                    //new
                    adminModel.SelectedAccountInfo = null;
                }
                else
                {
                    ViewBag.EditScreenHeader = "Edit Admin User";
                    //Update
                    adminModel.SelectedAccountInfo = AdminUserRepository.GetAdminUser(AdminUserID);
                }

                if (!string.IsNullOrEmpty(ErrorMessage))
                {
                    adminModel.ErrorMessage = ErrorMessage;
                    adminModel.SelectedAccountInfo = holdAdminUser;
                }

                return View(adminModel);
            }
            catch
            {
                return RedirectToAction("Login");
            }
        }

        [HttpPost]
        public ActionResult Delete(AdminModel adminModel)
        {
            Data data = new Data();
            string message = data.Delete(new TBL_ADMINUSER(), adminModel.AreChecked, "ADMINUSERID");

            return RedirectToAction("ListScreen");
        }

        [HttpPost]
        public ActionResult Update(TBL_ADMINUSER SelectedAccountInfo)
        {
            var result = string.Empty;
            Data data = new Data();
            if(SelectedAccountInfo.ADMINUSERID == new Guid())
            {
                //Save
                SelectedAccountInfo.CREATEDBY = this.Session["ADMINID"].ToString();
                // If new user, default username and password will be the firstname of the user
                SelectedAccountInfo.USERNAME = SelectedAccountInfo.FIRSTNAME.ToString().ToLower();
                SelectedAccountInfo.PASSWORD = SelectedAccountInfo.FIRSTNAME.ToString().ToLower();

                result = data.Save(SelectedAccountInfo, new List<string> { "ADMINUSERID" }, "ADMINUSERID");
            }
            else
            {
                //Update
                TBL_ADMINUSER AdminUser = SelectedAccountInfo;
                TBL_ADMINUSER filter = new TBL_ADMINUSER();
                filter.ADMINUSERID = AdminUser.ADMINUSERID;
                AdminUser.ADMINUSERID = new Guid();
                result = data.Update(AdminUser, filter, new Guid(this.Session["ADMINID"].ToString()));
            }
            if(result != "Success")
            {
                Guid x;
                if (!Guid.TryParse(result, out x)) // check if return value is not UID
                {
                    ErrorMessage = result;
                    holdAdminUser = SelectedAccountInfo as TBL_ADMINUSER;
                    return Redirect(Request.UrlReferrer.ToString());
                }
            }
            ErrorMessage = string.Empty;
            holdAdminUser = new TBL_ADMINUSER();
            return RedirectToAction("ListScreen");
        }
    }
}

AccessSystem/Controllers/ComputerController.cs
using AccessSystem.Model;
using AccessSystem.Repository;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace AccessSystem.Controllers
{
    public class ComputerController : Controller
    {
        static string ErrorMessage = string.Empty;
        static TBL_COMPUTER holdComputer = new TBL_COMPUTER();
        public ActionResult ListScreen()
        {
            try
            {
                // reset error Message and hold data when going to list screen
                ErrorMessage = string.Empty;
                holdComputer = new TBL_COMPUTER();

                if (string.IsNullOrEmpty(this.Session["ADMINID"].ToString()))
                {
                    return RedirectToAction("Login");
                }
                string adminAccountID = this.Session["ADMINID"].ToString();

                AdminModel adminModel = new AdminModel();
                adminModel.AccountInfo = AdminUserRepository.GetCurrentUserInfo(new Guid(adminAccountID));
                ViewBag.Firstname = adminModel.AccountInfo.FIRSTNAME;

                adminModel.ComputerList = ComputerRepository.GetComputers();

                return View(adminModel);
            }
            catch
            {
                return RedirectToAction("Login");
            }
        }

        public ActionResult EditScreen(Guid? computerID)
        {
            try
            {
                if (string.IsNullOrEmpty(this.Session["ADMINID"].ToString()))
                {
                    return RedirectToAction("Login");
                }
                string adminAccountID = this.Session["ADMINID"].ToString();

                AdminModel adminModel = new AdminModel();
                adminModel.AccountInfo = AdminUserRepository.GetCurrentUserInfo(new Guid(adminAccountID));
                ViewBag.Firstname = adminModel.AccountInfo.FIRSTNAME;

                if (computerID == null)
                {
                    ViewBag.EditScreenHeader = "Add Computer";
                    //new
                    adminModel.SelectedComputer = null;
                }
                else
                {
                    ViewBag.EditScreenHeader = "Edit Computer";
                    //Update
                    adminModel.SelectedComputer = ComputerRepository.GetComputerInfo(computerID);
                }

                if (!string.IsNullOrEmpty(ErrorMessage))
                {
                    adminModel.ErrorMessage = ErrorMessage;
                    adminModel.SelectedComputer = holdComputer;
                }

                return View(adminModel);
            }
            catch
            {
                return RedirectToAction("Login");
            }
        }

        [HttpPost]
        public ActionResult Delete(AdminModel adminModel)
        {
            Data data = new Data();
            string message = data.Delete(new TBL_COMPUTER(), adminModel.AreChecked, "COMPUTERID");

            return RedirectToAction("ListScreen");
        }

        [HttpPost]
        public ActionResult Update(TBL_COMPUTER SelectedComputer)
        {
            var result = string.Empty;
            Data data = new Data();
            if (SelectedComputer.COMPUTERID == new Guid())
            {
                //Save

                result = data.Save(SelectedComputer, new List<string> { "COMPUTERID" }, "COMPUTERID");
            }
            else
            {
                //Update
                TBL_COMPUTER Computer = SelectedComputer;
                TBL_COMPUTER filter = new TBL_COMPUTER();
                filter.COMPUTERID = Computer.COMPUTERID;
                Computer.COMPUTERID = new Guid();
                result = data.Update(Computer, filter, new Guid(this.Session["ADMINID"].ToString()));
            }
            if (result != "Success")
            {
                Guid x;
                if (!Guid.TryParse(result, out x)) // check if return value is not UID
                {
                    ErrorMessage = result;
                    holdComputer = SelectedComputer as TBL_COMPUTER;
                    return Redirect(Request.UrlReferrer.ToString());
                }
            }
            ErrorMessage = string.Empty;
            holdComputer = new TBL_COMPUTER();
            return RedirectToAction("ListScreen");
        }
    }
}

AccessSystem/Controllers/LoggingController.cs
using AccessSystem.Model;
using AccessSystem.Repository;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace AccessSystem.Controllers
{
    public class LoggingController : Controller
    {
        static string ErrorMessage = string.Empty;
        static TBL_LOG holdlog = new TBL_LOG();
        static bool isNew = false;
        public ActionResult ListScreen()
        {
            try
            {
                // reset error Message and hold data when going to list screen
                ErrorMessage = string.Empty;
                holdlog = new TBL_LOG();

                if (string.IsNullOrEmpty(this.Session["ADMINID"].ToString()))
                {
                    return RedirectToAction("Login");
                }
                string adminAccountID = this.Session["ADMINID"].ToString();

                AdminModel adminModel = new AdminModel();
                adminModel.AccountInfo = AdminUserRepository.GetCurrentUserInfo(new Guid(adminAccountID));
                ViewBag.Firstname = adminModel.AccountInfo.FIRSTNAME;

                adminModel.LogList = DataLogsRepository.GetAllLogs();

                return View(adminModel);
            }
            catch
            {
                return RedirectToAction("Login");
            }
        }
        public ActionResult EditScreen(Guid? LogID)
        {
            try
            {
                if (string.IsNullOrEmpty(this.Session["ADMINID"].ToString()))
                {
                    return RedirectToAction("Login");
                }
                string adminAccountID = this.Session["ADMINID"].ToString();

                AdminModel adminModel = new AdminModel();
                adminModel.AccountInfo = AdminUserRepository.GetCurrentUserInfo(new Guid(adminAccountID));
                ViewBag.Firstname = adminModel.AccountInfo.FIRSTNAME;

                adminModel.UserList = UserRepository.GetAllUsers();
                adminModel.ComputerList = ComputerRepository.GetComputers();

                if (LogID == null)
                {
                    ViewBag.EditScreenHeader = "Add Log";
                    //new
                    adminModel.SelectedLog = null;
                }
                else
                {
                    ViewBag.EditScreenHeader = "Edit Log";
                    //Update
                    adminModel.SelectedLog = DataLogsRepository.GetLog(LogID);
                }

                if (!string.IsNullOrEmpty(ErrorMessage))
                {
                    adminModel.ErrorMessage = ErrorMessage;
                    adminModel.SelectedLog = holdlog;
                }

                return View(adminModel);
            }
            catch
            {
                return RedirectToAction("Login");
            }
        }
        [HttpPost]
        public ActionResult Delete(AdminModel adminModel)
        {
            Data data = new Data();
            string message = data.Delete(new TBL_LOG(), adminModel.AreChecked, "LOGID");

            return RedirectToAction("ListScreen");
        }

        [HttpPost]
        public ActionResult Update(TBL_LOG SelectedLog)
        {
            var result = string.Empty;
            Data data = new Data();
            if (SelectedLog.LOGID == new Guid())
            {
                //Save

                result = data.Save(SelectedLog, new List<string> { "LOGID" }, "LOGID");
                isNew = true;
            }
            else
            {
                //Update
                TBL_LOG log = SelectedLog;
                TBL_LOG filter = new TBL_LOG();
                filter.LOGID = log.LOGID;
                log.LOGID = new Guid();
                result = data.Update(log, filter, new Guid(this.Session["ADMINID"].ToString()));
                isNew = false;
            }
            if (result != "Success")
            {
                Guid x;
                if (!Guid.TryParse(result, out x)) // check if return value is not UID
                {
                    ErrorMessage = result;
                    holdlog = SelectedLog as TBL_LOG;
                    return Redirect(Request.UrlReferrer.ToString());
                }
            }
            ErrorMessage = string.Empty;
            holdlog = new TBL_LOG();
            if (isNew)
            {
                holdlog = SelectedLog;
                holdlog.NAMEID = new Guid(result);
                //return RedirectToAction("RegisterFaceRFID");
            }
            return RedirectToAction("ListScreen");
        }
    }
}

AccessSystem/Views/Shared/_AdminLayout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Doorlock System</title>
    <script src="~/Scripts/popper.js" crossorigin="anonymous"></script>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    @Scripts.Render("~/bundles/jquery")
    @Styles.Render("~/bundles/Table_Style")
    @Scripts.Render("~/bundles/Table")
    <script type="text/javascript" src="https://unpkg.com/webcam-easy/dist/webcam-easy.min.js"></script>
    <link rel="stylesheet" href="//netdna.bootstrapcdn.com/font-awesome/3.2.1/css/font-awesome.css">
</head>
<body>
    <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-dark bg-dark">
        <div class="container">
            @*@Html.ActionLink("Access System", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })*@
            <a class="navbar-brand">Smart RFID Doorlock System</a>
            <button type="button" class="navbar-toggler" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" title="Toggle navigation" aria-controls="navbarSupportedContent"
                    aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse d-sm-inline-flex justify-content-between">
                <ul class="navbar-nav flex-grow-1">
                    <li>@Html.ActionLink("Computers", "ListScreen", "Computer", new { area = "" }, new { @class = "nav-link" })</li>
                    <li>@Html.ActionLink("Users", "ListScreen", "Users", new { area = "" }, new { @class = "nav-link" })</li>
                    <li>@Html.ActionLink("Admin Users", "ListScreen", "AdminUser", new { area = "" }, new { @class = "nav-link" })</li>
                    <li>@Html.ActionLink("Logs", "ListScreen", "Logging", new { area = "" }, new { @class = "nav-link" })</li>
                </ul>
                <form class="d-flex">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" data-bs-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false"> @ViewBag.FirstName </a>
                            <div class="dropdown-menu">
                                @Html.ActionLink("Account Settings", "AccountSettings", "Home", new { area = "" }, new { @class = "dropdown-item" })
                                <div class="dropdown-divider"></div>
                                @Html.ActionLink("Logout", "Logout", "Home", new { area = "" }, new { @class = "dropdown-item" })
                            </div>
                        </li>
                    </ul>
                </form>
            </div>
        </div>
    </nav>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Smart RFID Doorlock System</p>
        </footer>
    </div>

    
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

AccessSystem/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Doorlock System</title>

    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    <script type="text/javascript" src="https://unpkg.com/webcam-easy/dist/webcam-easy.min.js"></script>
</head>
<body>
    <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-dark bg-dark">
        <div class="container">
            @*@Html.ActionLink("Acess System", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })*@
            <a class="navbar-brand">Smart RFID Doorlock System</a>
            <button type="button" class="navbar-toggler" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" title="Toggle navigation" aria-controls="navbarSupportedContent"
                    aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse d-sm-inline-flex justify-content-between">
                <ul class="navbar-nav flex-grow-1">
                    <li>@Html.ActionLink("Home", "Home", "Home", new { area = "" }, new { @class = "nav-link" })</li>
                    <li>@Html.ActionLink("Logging", "Index", "Home", new { area = "" }, new { @class = "nav-link" })</li>
                </ul>
                <form class="d-flex">
                    <ul class="navbar-nav flex-grow-1">
                        <li>@Html.ActionLink("Login", "Login", "Home", new { area = "" }, new { @class = "nav-link" })</li>
                    </ul>
                </form>
            </div>
        </div>
    </nav>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Smart RFID Doorlock System</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>