AccessSystem/Controllers/LogController.cs
using AccessSystem.Model;
using AccessSystem.Repository;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace AccessSystem.Controllers
{
    public class LogController : Controller
    {
        static string ErrorMessage = string.Empty;
        static TBL_LOG holdlog = new TBL_LOG();
        static bool isNew = false;
        public ActionResult ListScreen()
        {
            try
            {
                // reset error Message and hold data when going to list screen
                ErrorMessage = string.Empty;
                holdlog = new TBL_LOG();

                if (string.IsNullOrEmpty(this.Session["ADMINID"].ToString()))
                {
                    return RedirectToAction("Login");
                }
                string adminAccountID = this.Session["ADMINID"].ToString();

                AdminModel adminModel = new AdminModel();
                adminModel.AccountInfo = AdminUserRepository.GetCurrentUserInfo(new Guid(adminAccountID));
                ViewBag.Firstname = adminModel.AccountInfo.FIRSTNAME;

                adminModel.LogList = DataLogsRepository.GetAllLogs();

                return View(adminModel);
            }
            catch
            {
                return RedirectToAction("Login");
            }
        }
        public ActionResult EditScreen(Guid? LogID)
        {
            try
            {
                if (string.IsNullOrEmpty(this.Session["ADMINID"].ToString()))
                {
                    return RedirectToAction("Login");
                }
                string adminAccountID = this.Session["ADMINID"].ToString();

                AdminModel adminModel = new AdminModel();
                adminModel.AccountInfo = AdminUserRepository.GetCurrentUserInfo(new Guid(adminAccountID));
                ViewBag.Firstname = adminModel.AccountInfo.FIRSTNAME;

                adminModel.UserList = UserRepository.GetAllUsers();
                adminModel.ComputerList = ComputerRepository.GetComputers();

                if (LogID == null)
                {
                    ViewBag.EditScreenHeader = "Add Log";
                    //new
                    adminModel.SelectedLog = null;
                }
                else
                {
                    ViewBag.EditScreenHeader = "Edit Log";
                    //Update
                    adminModel.SelectedLog = DataLogsRepository.GetLog(LogID);
                }

                if (!string.IsNullOrEmpty(ErrorMessage))
                {
                    adminModel.ErrorMessage = ErrorMessage;
                    adminModel.SelectedLog = holdlog;
                }

                return View(adminModel);
            }
            catch
            {
                return RedirectToAction("Login");
            }
        }
        [HttpPost]
        public ActionResult Delete(AdminModel adminModel)
        {
            Data data = new Data();
            string message = data.Delete(new TBL_LOG(), adminModel.AreChecked, "LOGID");

            return RedirectToAction("ListScreen");
        }

        [HttpPost]
        public ActionResult Update(TBL_LOG SelectedLog)
        {
            var result = string.Empty;
            Data data = new Data();
            if (SelectedLog.LOGID == new Guid())
            {
                //Save

                result = data.Save(SelectedLog, new List<string> { "LOGID" }, "LOGID");
                isNew = true;
            }
            else
            {
                //Update
                TBL_LOG log = SelectedLog;
                TBL_LOG filter = new TBL_LOG();
                filter.LOGID = log.LOGID;
                log.LOGID = new Guid();
                result = data.Update(log, filter, new Guid(this.Session["ADMINID"].ToString()));
                isNew = false;
            }
            if (result != "Success")
            {
                Guid x;
                if (!Guid.TryParse(result, out x)) // check if return value is not UID
                {
                    ErrorMessage = result;
                    holdlog = SelectedLog as TBL_LOG;
                    return Redirect(Request.UrlReferrer.ToString());
                }
            }
            ErrorMessage = string.Empty;
            holdlog = new TBL_LOG();
            if (isNew)
            {
                holdlog = SelectedLog;
                holdlog.NAMEID = new Guid(result);
                //return RedirectToAction("RegisterFaceRFID");
            }
            return RedirectToAction("ListScreen");
        }
    }
}

AccessSystem/Controllers/LoggingController.cs
using AccessSystem.Model;
using AccessSystem.Repository;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace AccessSystem.Controllers
{
    public class LoggingController : Controller
    {
        static string ErrorMessage = string.Empty;
        static TBL_LOG holdlog = new TBL_LOG();
        static bool isNew = false;
        public ActionResult ListScreen()
        {
            try
            {
                // reset error Message and hold data when going to list screen
                ErrorMessage = string.Empty;
                holdlog = new TBL_LOG();

                if (string.IsNullOrEmpty(this.Session["ADMINID"].ToString()))
                {
                    return RedirectToAction("Login");
                }
                string adminAccountID = this.Session["ADMINID"].ToString();

                AdminModel adminModel = new AdminModel();
                adminModel.AccountInfo = AdminUserRepository.GetCurrentUserInfo(new Guid(adminAccountID));
                ViewBag.Firstname = adminModel.AccountInfo.FIRSTNAME;

                adminModel.LogList = DataLogsRepository.GetAllLogs();

                return View(adminModel);
            }
            catch
            {
                return RedirectToAction("Login");
            }
        }
        public ActionResult EditScreen(Guid? LogID)
        {
            try
            {
                if (string.IsNullOrEmpty(this.Session["ADMINID"].ToString()))
                {
                    return RedirectToAction("Login");
                }
                string adminAccountID = this.Session["ADMINID"].ToString();

                AdminModel adminModel = new AdminModel();
                adminModel.AccountInfo = AdminUserRepository.GetCurrentUserInfo(new Guid(adminAccountID));
                ViewBag.Firstname = adminModel.AccountInfo.FIRSTNAME;

                adminModel.UserList = UserRepository.GetAllUsers();
                adminModel.ComputerList = ComputerRepository.GetComputers();

                if (LogID == null)
                {
                    ViewBag.EditScreenHeader = "Add Log";
                    //new
                    adminModel.SelectedLog = null;
                }
                else
                {
                    ViewBag.EditScreenHeader = "Edit Log";
                    //Update
                    adminModel.SelectedLog = DataLogsRepository.GetLog(LogID);
                }

                if (!string.IsNullOrEmpty(ErrorMessage))
                {
                    adminModel.ErrorMessage = ErrorMessage;
                    adminModel.SelectedLog = holdlog;
                }

                return View(adminModel);
            }
            catch
            {
                return RedirectToAction("Login");
            }
        }
        [HttpPost]
        public ActionResult Delete(AdminModel adminModel)
        {
            Data data = new Data();
            string message = data.Delete(new TBL_LOG(), adminModel.AreChecked, "LOGID");

            return RedirectToAction("ListScreen");
        }

        [HttpPost]
        public ActionResult Update(TBL_LOG SelectedLog)
        {
            var result = string.Empty;
            Data data = new Data();
            if (SelectedLog.LOGID == new Guid())
            {
                //Save

                result = data.Save(SelectedLog, new List<string> { "LOGID" }, "LOGID");
                isNew = true;
            }
            else
            {
                //Update
                TBL_LOG log = SelectedLog;
                TBL_LOG filter = new TBL_LOG();
                filter.LOGID = log.LOGID;
                log.LOGID = new Guid();
                result = data.Update(log, filter, new Guid(this.Session["ADMINID"].ToString()));
                isNew = false;
            }
            if (result != "Success")
            {
                Guid x;
                if (!Guid.TryParse(result, out x)) // check if return value is not UID
                {
                    ErrorMessage = result;
                    holdlog = SelectedLog as TBL_LOG;
                    return Redirect(Request.UrlReferrer.ToString());
                }
            }
            ErrorMessage = string.Empty;
            holdlog = new TBL_LOG();
            if (isNew)
            {
                holdlog = SelectedLog;
                holdlog.NAMEID = new Guid(result);
                //return RedirectToAction("RegisterFaceRFID");
            }
            return RedirectToAction("ListScreen");
        }
    }
}

AccessSystem/Views/Logging/EditScreen.cshtml
@model AccessSystem.Model.AdminModel
@{
    ViewBag.Title = "Edit Log";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<div class="alert alert-dismissible alert-danger @(String.IsNullOrEmpty(Model.ErrorMessage)?"hidden":"")">
    <button type="button" class="btn-close" data-bs-dismiss="alert"></button>
    <h4 class="alert-heading">Error!!!</h4>
    <p class="mb-0">@Model.ErrorMessage</p>
</div>
<div class="card" style="">
    <div class="card-header">@ViewBag.EditScreenHeader</div>
    <div class="card-body">
        @using (Html.BeginForm("Update", "Logging", FormMethod.Post, new { @name = "LogForm" }))
        {
            <fieldset>
                @* Add class row if viewing *@
                @Html.TextBoxFor(model => model.SelectedLog.LOGID, new { @class = "hidden", @id = "LOGID" })
                <div class="form-group row margin_bottom_10">
                    <label for="Name" class="col-sm-2 col-form-label">Name</label>
                    <div class="col-sm-10">
                        @{
                            var usersSelectList = new List<SelectListItem>();
                            foreach (var users in Model.UserList)
                            {
                                usersSelectList.Add(new SelectListItem { Text = users.FIRSTNAME + " " + users.LASTNAME, Value = users.NAMEID.ToString() });
                            }
                        }
                        @Html.DropDownListFor(model => model.SelectedLog.NAMEID, usersSelectList, "Select User...", new { @class = "form-select", @id = "NAMEID" })
                    </div>
                </div>

                <div class="form-group row margin_bottom_10">
                    <label for="Name" class="col-sm-2 col-form-label">Computer number</label>
                    <div class="col-sm-10">
                        @{
                            var computerList = new List<SelectListItem>();
                            foreach (var computers in Model.ComputerList)
                            {
                                computerList.Add(new SelectListItem { Text = computers.COMPUTERNUMBER.ToString(), Value = computers.COMPUTERID.ToString() });
                            }
                        }
                        @Html.DropDownListFor(model => model.SelectedLog.COMPUTERID, computerList, "Select Computers...", new { @class = "form-select", @id = "COMPUTERID" })
                    </div>
                </div>

                <div class="form-group row margin_bottom_10">
                    <label for="Name" class="col-sm-2 col-form-label">Start Time</label>
                    <div class="col-sm-10">
                        @* class should be form-control-plaintext when viewing *@
                        @Html.TextBoxFor(model => model.SelectedLog.STARTTIME, "{0:yyyy-MM-ddTHH:mm}", new { @class = "form-control", @id = "STARTTIME", @type= "datetime-local" })
                    </div>
                </div>

                <div class="form-group row margin_bottom_10">
                    <label for="Name" class="col-sm-2 col-form-label">End Time</label>
                    <div class="col-sm-10">
                        @* class should be form-control-plaintext when viewing *@
                        @Html.TextBoxFor(model => model.SelectedLog.ENDTIME, "{0:yyyy-MM-ddTHH:mm}", new { @class = "form-control", @id = "ENDTIME", @type = "datetime-local" })
                    </div>
                </div>

                <button type="submit" class="btn btn-success" href=""><i class="icon-save"></i>  Save</button>
                <a class="btn btn-primary" href="@Url.Action("ListScreen","Logging")"><i class="icon-chevron-left"></i>  Back</a>
            </fieldset>
        }

    </div>
</div>

AccessSystem/Views/Logging/ListScreen.cshtml
@model AccessSystem.Model.AdminModel
@{
    ViewBag.Title = "Logs List Screen";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}
@*<script src="https://cdn.datatables.net/1.13.4/js/jquery.dataTables.min.js"></script>*@
<script src="https://cdn.datatables.net/buttons/2.3.6/js/dataTables.buttons.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/jszip/3.1.3/jszip.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/pdfmake/0.1.53/pdfmake.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/pdfmake/0.1.53/vfs_fonts.js"></script>
<script src="https://cdn.datatables.net/buttons/2.3.6/js/buttons.html5.min.js"></script>
<script src="https://cdn.datatables.net/buttons/2.3.6/js/buttons.print.min.js"></script>

@using (Html.BeginForm("Delete", "Logging", FormMethod.Post, new { @name = "LogForm" }))
{
    <legend>Logs List Screen</legend>
    <p class="bs-component">
        <a class="btn btn-primary" href="@Url.Action("EditScreen","Log")"><i class="icon-plus"></i>  Add</a>
        <button type="submit" class="btn btn-danger"><i class="icon-trash"></i>  Delete</button>
    </p>
    <table id="LogTable" class="table table-striped" style="width:100%">
        <thead>
            <tr>
                <th style="width: 25px;">
                    @*<input type="checkbox" id="AreChecked" />*@
                </th>
                <th>Full Name</th>
                <th>Course, Year and Section</th>
                <th>Computer Number</th>
                <th>Start Time</th>
                <th>End Time</th>
                <th class="hidden">ID</th>
            </tr>
        </thead>
        <tbody>
            @foreach (AccessSystem.Model.TBL_LOG log in Model.LogList)
            {
                <tr>
                    <td><input type="checkbox" name="AreChecked" value="@log.LOGID" /></td>
                    <td><a href="@Url.Action("EditScreen","Logging", new { LogID = (log.LOGID)})">@log.TBL_NAMES.FIRSTNAME @log.TBL_NAMES.LASTNAME</a></td>
                    <td>@log.TBL_NAMES.TBL_COURSEANDSECTION.COURSE @log.TBL_NAMES.TBL_COURSEANDSECTION.YEAR - @log.TBL_NAMES.TBL_COURSEANDSECTION.SECTION</td>
                    <td>@log.TBL_COMPUTER.COMPUTERNUMBER</td>
                    <td>@log.STARTTIME</td>
                    <td>@log.ENDTIME</td>
                    <td class="hidden">@log.LOGID</td>
                </tr>
            }
        </tbody>
    </table>
}

<script>
    $(document).ready(function () {
        $('#LogTable').DataTable({
            dom: 'Bfrtip',
            buttons: [
                'copy', 'csv', 'excel', 'pdf', 'print'
            ],
            "columnDefs": [
                { "orderable": false, "targets": 0 }
            ],
            order: [[4, 'desc']],
            "pagingType": $(".container-fluid").width() <= 480 ? "simple" : "simple_numbers"
        });

        $("button").addClass("btn btn-primary");
    });
</script>