AccessSystem/Controllers/CourseSectionController.cs
using AccessSystem.Model;
using AccessSystem.Repository;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace AccessSystem.Controllers
{
    public class CourseSectionController : Controller
    {
        static string ErrorMessage = string.Empty;
        static TBL_COURSEANDSECTION holdCourseSection = new TBL_COURSEANDSECTION();
        public ActionResult ListScreen()
        {
            try
            {
                // reset error Message and hold data when going to list screen
                ErrorMessage = string.Empty;
                holdCourseSection = new TBL_COURSEANDSECTION();

                if (string.IsNullOrEmpty(this.Session["ADMINID"].ToString()))
                {
                    return RedirectToAction("Login");
                }
                string adminAccountID = this.Session["ADMINID"].ToString();

                AdminModel adminModel = new AdminModel();
                adminModel.AccountInfo = AdminUserRepository.GetCurrentUserInfo(new Guid(adminAccountID));
                ViewBag.Firstname = adminModel.AccountInfo.FIRSTNAME;

                adminModel.CourseSectionList = CourseSectionRepository.GetAllCourseSection();

                return View(adminModel);
            }
            catch
            {
                return RedirectToAction("Login");
            }
        }

        public ActionResult EditScreen(Guid? CourseSectionID)
        {
            try
            {
                if (string.IsNullOrEmpty(this.Session["ADMINID"].ToString()))
                {
                    return RedirectToAction("Login");
                }
                string adminAccountID = this.Session["ADMINID"].ToString();

                AdminModel adminModel = new AdminModel();
                adminModel.AccountInfo = AdminUserRepository.GetCurrentUserInfo(new Guid(adminAccountID));
                ViewBag.Firstname = adminModel.AccountInfo.FIRSTNAME;

                if (CourseSectionID == null)
                {
                    ViewBag.EditScreenHeader = "Add Course and Section";
                    //new
                    adminModel.SelectedCourseSection = null;
                }
                else
                {
                    ViewBag.EditScreenHeader = "Edit Course and Section";
                    //Update
                    adminModel.SelectedCourseSection = CourseSectionRepository.GetAllCourseSectionWithID(CourseSectionID);
                }

                if (!string.IsNullOrEmpty(ErrorMessage))
                {
                    adminModel.ErrorMessage = ErrorMessage;
                    adminModel.SelectedCourseSection = holdCourseSection;
                }

                return View(adminModel);
            }
            catch
            {
                return RedirectToAction("Login");
            }
        }

        [HttpPost]
        public ActionResult Delete(AdminModel adminModel)
        {
            Data data = new Data();
            string message = data.Delete(new TBL_COURSEANDSECTION(), adminModel.AreChecked, "COURSESECTIONID");

            return RedirectToAction("ListScreen");
        }

        [HttpPost]
        public ActionResult Update(TBL_COURSEANDSECTION SelectedCourseSection)
        {
            var result = string.Empty;
            Data data = new Data();
            if (SelectedCourseSection.COURSESECTIONID == new Guid())
            {
                //Save

                result = data.Save(SelectedCourseSection, new List<string> { "COURSESECTIONID" }, "COURSESECTIONID");
            }
            else
            {
                //Update
                TBL_COURSEANDSECTION CourseSection = SelectedCourseSection;
                TBL_COURSEANDSECTION filter = new TBL_COURSEANDSECTION();
                filter.COURSESECTIONID = CourseSection.COURSESECTIONID;
                CourseSection.COURSESECTIONID = new Guid();
                result = data.Update(CourseSection, filter, new Guid(this.Session["ADMINID"].ToString()));
            }
            if (result != "Success")
            {
                Guid x;
                if (!Guid.TryParse(result, out x)) // check if return value is not UID
                {
                    ErrorMessage = result;
                    holdCourseSection = SelectedCourseSection as TBL_COURSEANDSECTION;
                    return Redirect(Request.UrlReferrer.ToString());
                }
            }
            ErrorMessage = string.Empty;
            holdCourseSection = new TBL_COURSEANDSECTION();
            return RedirectToAction("ListScreen");
        }
    }
}

AccessSystem/Controllers/UsersController.cs
using AccessSystem.Model;
using AccessSystem.Repository;
using System;
using System.Collections.Generic;
using System.Drawing;
using System.Drawing.Imaging;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace AccessSystem.Controllers
{
    public class UsersController : Controller
    {
        static string ErrorMessage = string.Empty;
        static TBL_NAMES holdUser = new TBL_NAMES();
        static bool isNew = false;
        public ActionResult ListScreen()
        {
            try
            {
                // reset error Message and hold data when going to list screen
                ErrorMessage = string.Empty;
                holdUser = new TBL_NAMES();

                if (string.IsNullOrEmpty(this.Session["ADMINID"].ToString()))
                {
                    return RedirectToAction("Login");
                }
                string adminAccountID = this.Session["ADMINID"].ToString();

                AdminModel adminModel = new AdminModel();
                adminModel.AccountInfo = AdminUserRepository.GetCurrentUserInfo(new Guid(adminAccountID));
                ViewBag.Firstname = adminModel.AccountInfo.FIRSTNAME;

                adminModel.UserList = UserRepository.GetAllUsers();

                return View(adminModel);
            }
            catch
            {
                return RedirectToAction("Login");
            }
        }

        public ActionResult EditScreen(Guid? NameID)
        {
            try
            {
                if (string.IsNullOrEmpty(this.Session["ADMINID"].ToString()))
                {
                    return RedirectToAction("Login");
                }
                string adminAccountID = this.Session["ADMINID"].ToString();

                AdminModel adminModel = new AdminModel();
                adminModel.AccountInfo = AdminUserRepository.GetCurrentUserInfo(new Guid(adminAccountID));
                ViewBag.Firstname = adminModel.AccountInfo.FIRSTNAME;

                adminModel.CourseSectionList = CourseSectionRepository.GetAllCourseSection();

                if (NameID == null)
                {
                    ViewBag.EditScreenHeader = "Add User";
                    //new
                    adminModel.SelectedUser = null;
                }
                else
                {
                    ViewBag.EditScreenHeader = "Edit User";
                    //Update
                    adminModel.SelectedUser = UserRepository.GetUser(NameID);
                }

                if (!string.IsNullOrEmpty(ErrorMessage))
                {
                    adminModel.ErrorMessage = ErrorMessage;
                    adminModel.SelectedUser = holdUser;
                }

                return View(adminModel);
            }
            catch
            {
                return RedirectToAction("Login");
            }
        }

        [HttpPost]
        public ActionResult Delete(AdminModel adminModel)
        {
            Data data = new Data();
            string message = data.Delete(new TBL_NAMES(), adminModel.AreChecked, "NAMEID");

            return RedirectToAction("ListScreen");
        }

        [HttpPost]
        public ActionResult Update(TBL_NAMES SelectedUser)
        {
            var result = string.Empty;
            Data data = new Data();
            if (SelectedUser.NAMEID == new Guid())
            {
                //Save

                result = data.Save(SelectedUser, new List<string> { "NAMEID" }, "NAMEID");
                isNew = true;
            }
            else
            {
                //Update
                TBL_NAMES Name = SelectedUser;
                TBL_NAMES filter = new TBL_NAMES();
                filter.NAMEID = Name.NAMEID;
                Name.NAMEID = new Guid();
                result = data.Update(Name, filter, new Guid(this.Session["ADMINID"].ToString()));
                isNew = false;
            }
            if (result != "Success")
            {
                Guid x;
                if (!Guid.TryParse(result, out x)) // check if return value is not UID
                {
                    ErrorMessage = result;
                    holdUser = SelectedUser as TBL_NAMES;
                    return Redirect(Request.UrlReferrer.ToString());
                }
            }
            ErrorMessage = string.Empty;
            holdUser = new TBL_NAMES();
            if(isNew)
            {
                holdUser = SelectedUser;
                holdUser.NAMEID = new Guid(result);
                return RedirectToAction("RegisterFaceRFID");
            }
            return RedirectToAction("ListScreen");
        }

        public ActionResult RegisterFaceRFID()
        {
            try
            {
                if (string.IsNullOrEmpty(this.Session["ADMINID"].ToString()))
                {
                    return RedirectToAction("Login");
                }
                string adminAccountID = this.Session["ADMINID"].ToString();

                AdminModel adminModel = new AdminModel();
                adminModel.AccountInfo = AdminUserRepository.GetCurrentUserInfo(new Guid(adminAccountID));
                ViewBag.Firstname = adminModel.AccountInfo.FIRSTNAME;

                adminModel.CourseSectionList = CourseSectionRepository.GetAllCourseSection();
                adminModel.SelectedUser = holdUser;

                return View(adminModel);
            }
            catch
            {
                return RedirectToAction("Login");
            }
        }

        [HttpPost]
        public string Capture(string ImageByteText, string FolderName, string captureNumber)
        {
            //byte[] bitmap = hdnimageBytes.Value;
            var t = ImageByteText.Substring(22);  // remove data:image/png;base64,
            byte[] bitmap = Convert.FromBase64String(t);
            using (Image image = Image.FromStream(new MemoryStream(bitmap)))
            {
                createDirectory(FolderName);

                string folderPath = Server.MapPath("~/Scripts/label/" + FolderName + "/");
                string fileName = captureNumber + ".jpg";
                string imagePath = folderPath + fileName;

                image.Save(imagePath, ImageFormat.Jpeg); // Or Png 
            }
            return "Image Saved";
        }

        public void createDirectory(string FolderName)
        {
            string dir = Server.MapPath("~/Scripts/label/" + FolderName);
            if (!Directory.Exists(dir))
            {
                Directory.CreateDirectory(dir);
            }
        }
    }
}

AccessSystem/Views/Users/ListScreen.cshtml
@{
    ViewBag.Title = "Users List";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}


@using (Html.BeginForm("Delete", "Users", FormMethod.Post, new { @name = "UsersForm" }))
{
    <legend>Users List</legend>
    <p class="bs-component">
        <a class="btn btn-primary" href="@Url.Action("EditScreen","Users")"><i class="icon-plus"></i>  Add</a>
        <button type="submit" class="btn btn-danger"><i class="icon-trash"></i>  Delete</button>
        <a class="btn btn-outline-primary" href="@Url.Action("ListScreen","CourseSection")"><i class="icon-list"></i>  Course, Year And Section List</a>
    </p>
    <table id="CourseSectionTable" class="table table-striped" style="width:100%">
        <thead>
            <tr>
                <th style="width: 25px;">
                    @*<input type="checkbox" id="AreChecked" />*@
                </th>
                <th>First Name</th>
                <th>Middle Name</th>
                <th>Last Name</th>
                <th>Course, Year and Section</th>
                <th class="hidden">ID</th>
            </tr>
        </thead>
        <tbody>
            @foreach (AccessSystem.Model.TBL_NAMES Users in Model.UserList)
            {
                <tr>
                    <td><input type="checkbox" name="AreChecked" value="@Users.NAMEID" /></td>
                    <td><a href="@Url.Action("EditScreen","Users", new { NameID = (Users.NAMEID)})">@Users.FIRSTNAME</a></td>
                    <td>@Users.MIDDLENAME</td>
                    <td>@Users.LASTNAME</td>
                    <td>@Users.TBL_COURSEANDSECTION.COURSE @Users.TBL_COURSEANDSECTION.YEAR - @Users.TBL_COURSEANDSECTION.SECTION</td>
                    <td class="hidden">@Users.NAMEID</td>
                </tr>
            }
        </tbody>
    </table>
}

<script>
    $(document).ready(function () {
        $('#CourseSectionTable').DataTable({
            "columnDefs": [
                { "orderable": false, "targets": 0 }
            ],
            order: [[1, 'asc']],
            "pagingType": $(".container-fluid").width() <= 480 ? "simple" : "simple_numbers"
        });
    });
</script>

AccessSystem/Views/Users/RegisterFaceRFID.cshtml
@model AccessSystem.Model.AdminModel
@{
    ViewBag.Title = "Register Face and RFID";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<div class="alert alert-dismissible alert-info">
    <button type="button" class="btn-close" data-bs-dismiss="alert"></button>
    <h4 class="alert-heading">Heads up!!</h4>
    <p class="mb-0" id="Message">Hello Please take 2 picture</p>
</div>
<div class="card" style="">
    <div class="card-header">@ViewBag.EditScreenHeader</div>
    <div class="card-body">
        <div class="row">
            <div class="col-lg-5">
                @using (Html.BeginForm("Update", "Users", FormMethod.Post, new { @name = "UsersForm" }))
                {
                    <fieldset>
                        @* Add class row if viewing *@
                        @Html.TextBoxFor(model => model.SelectedUser.NAMEID, new { @class = "hidden", @id = "NAMEID" })
                        <div class="form-group row margin_bottom_10">
                            <label for="Name" class="col-sm-4 col-form-label">First Name</label>
                            <div class="col-sm-10">
                                @* class should be form-control-plaintext when viewing *@
                                @Html.TextBoxFor(model => model.SelectedUser.FIRSTNAME, new { @class = "form-control-plaintext", @id = "FIRSTNAME", @readonly = "" })
                            </div>
                        </div>

                        <div class="form-group row margin_bottom_10">
                            <label for="Name" class="col-sm-4 col-form-label">Middle Name</label>
                            <div class="col-sm-10">
                                @* class should be form-control-plaintext when viewing *@
                                @Html.TextBoxFor(model => model.SelectedUser.MIDDLENAME, new { @class = "form-control-plaintext", @id = "MIDDLENAME", @readonly = "" })
                            </div>
                        </div>

                        <div class="form-group row margin_bottom_10">
                            <label for="Name" class="col-sm-4 col-form-label">Last Name</label>
                            <div class="col-sm-10">
                                @* class should be form-control-plaintext when viewing *@
                                @Html.TextBoxFor(model => model.SelectedUser.LASTNAME, new { @class = "form-control-plaintext", @id = "LASTNAME", @readonly = "" })
                            </div>
                        </div>

                        <div class="form-group row margin_bottom_10">
                            <label for="Name" class="col-sm-4 col-form-label">Course, Year and Section</label>
                            <div class="col-sm-10">
                                @{
                                    var CYS = new List<SelectListItem>();
                                    foreach (var Course in Model.CourseSectionList)
                                    {
                                        if (Course.ISACTIVE)
                                        {
                                            CYS.Add(new SelectListItem { Text = Course.COURSE + " " + Course.YEAR + "-" + Course.SECTION, Value = Course.COURSESECTIONID.ToString() });
                                        }
                                    }
                                }
                                @Html.DropDownListFor(model => model.SelectedUser.COURSESECTIONID, CYS, "Select Course, Year and Section", new { @class = "form-control-plaintext", @id = "COURSESECTIONID", @disabled = "true" })
                            </div>
                        </div>

                        <!--<div class="form-group row margin_bottom_10">
                            <label for="Name" class="col-sm-4 col-form-label">Please Take 2 </label>
                            <div class="col-sm-10">-->
                                @* class should be form-control-plaintext when viewing *@
                                @*@Html.TextBoxFor(model => model.SelectedUser.LASTNAME, new { @class = "form-control-plaintext", @id = "LASTNAME", @readonly = "" })*@
                            <!--</div>
                        </div>-->

                    </fieldset>
                }
            </div>
            <div class="col-lg-5">
                @using (Html.BeginForm("Capture", "Home", FormMethod.Post, new { @name = "captureForm" }))
                {
                    <video id="webcam" autoplay playsinline width="640" height="480"></video>
                    <canvas id="canvas" class="d-none"></canvas>
                    <audio id="snapSound" src="~/audio/snap.wav" preload="auto"></audio>
                    <button type="button" class="btn btn-primary" onclick="snap()">Capture</button>
                    @*<button type="submit" class="btn btn-warning">Back</button>*@
                    <image id="test"></image>


                }

            </div>

            @*<button type="submit" class="btn btn-success" href=""><i class="icon-save"></i>  Save</button>*@

            
        <script>
                var captureNumber = 0;
                const webcamElement = document.getElementById('webcam');
                const canvasElement = document.getElementById('canvas');
                const snapSoundElement = document.getElementById('snapSound');
                const webcam = new Webcam(webcamElement, 'user', canvasElement, snapSoundElement);
                webcam.start()
                    .then(result => {
                        console.log("webcam started");
                    })
                    .catch(err => {
                        console.log(err);
                    });

                function snap() {
                    let picture = webcam.snap();
                    $("#test").val(document.getElementById("canvas").toDataURL());

                    var file = document.getElementById("canvas").toDataURL();

                    var formdata = new FormData();
                    var folder = '@Html.Raw(Model.SelectedUser.NAMEID)';
                    formdata.append("ImageByteText", file);
                    formdata.append("FolderName", folder);
                    captureNumber++;
                    formdata.append("captureNumber", captureNumber.toString());

                    $.ajax({
                        url: "@Url.Action("Capture")",
                        type: "POST",
                        data: formdata,
                        processData: false,
                        contentType: false,
                        success: function (data) {
                            alert(data);
                            $("#Message").text("Hello Please take " + captureNumber.toString() + " picture");
                            if (captureNumber >= 2) {
                                var url = '@Url.Action("ListScreen", "Users")';
                                window.location.href = url;
                            }
                        }
                    });

                }
        </script>
            @*<a class="btn btn-primary" href="@Url.Action("ListScreen","Users")"><i class="icon-chevron-left"></i>  Back</a>*@

        </div>

    </div>
</div>